Sources/arm/App.hx

This commit improve command line arguments by adding:
- "--reload-mesh" : Reload the current mesh
- "--export-textures" + File Type + Export Preset + Path : Export textures to the path with the according preset and file type
- "--export-mesh" + Path : Export current mesh to the path
- "--b" or "--background" : Close ArmorPaint when all previous task are done (useful for quick texture export from another dcc app)

Improving of Command Line Arguments

---

Sources/arm/format/FbxBinaryParser.hx

Bug fix #363.
Sources:
- https://github.com/assimp/assimp/issues/838
- https://github.com/assimp/assimp/pull/1354

Bug fix for FBX Binary 7500

---

README.md

Added a method to the documentation for generating locale files for translation.

Document how to generate a locale file

---

Sources/arm/Project.hx
Sources/arm/io/ImportFont.hx
Sources/arm/ui/UISidebar.hx

And extracting the font name from the font file.
**This requires https://github.com/armory3d/Kromx/pull/11 as well.**
For example
Change  default.ttf to Roboto
Import font_cjk.ttc to import each font

Importing each font when you import ttc fonts

---

Sources/arm/Translator.hx

Please see https://github.com/armory3d/armorpaint/pull/496#issuecomment-657045644

Auto download cjk font

---

Sources/arm/Translator.hx

Restore font and size when switching languages

---

Sources/arm/node/NodesBrush.hx
Sources/arm/node/brush/MathNode.hx

I also added the ping-pong operation to brush math node.

Add Ping-Pong operation to brush math node

---

Sources/arm/Layers.hx

Prevent drag and drop image on masks and groups

---

Sources/arm/ui/TabLayers.hx

While duplicating layers and groups it will now duplicate all masks associated with the layers

Duplicate layers and groups

---

Sources/arm/ui/TabSwatches.hx

Reopening of:
https://github.com/armory3d/armorpaint/pull/1019
Implemented Feature Request / Bug:
https://github.com/armory3d/armorpaint/issues/1018
Right clicking swatches now selects them when you want to right click and delete, shows indicator over swatch right clicked

right clicking swatches

---

Sources/arm/data/LayerSlot.hx
Sources/arm/ui/TabLayers.hx

This PR gives the user feedback whether dropping a layer is possible or not. This implements the first part of #1014. The color for not being able to drop here is ACCENT_HOVER_COL. Feel free to change it
It also fixes #1028 and allows to drag a layer at the bottom.

Give visual feedback on layer drag

---

Sources/arm/ui/UIFiles.hx

Fix network paths on windows are always nested

---

Sources/arm/ui/TabBrowser.hx
Sources/arm/ui/UIFiles.hx

I improved the Browser in two ways.
1. I missed a function to refresh the current directory. This is useful for cases like having created new textures in a different application, while viewing the directory in the browser. What I dislike about my implementation is that a icon would look better than text.
2. Closing a current search is not really intuitive and also definitely not quick. I added a X-button to close it.

Add refresh and close search to browser

---

Sources/arm/ui/UIToolbar.hx

The ArmorPaint part of https://github.com/armory3d/armorbase/pull/11

Move _tr to Translator in armorbase

---

Sources/arm/ui/BoxPreferences.hx
Sources/arm/ui/TabSwatches.hx
Sources/arm/ui/UIHeader.hx

The ArmorPaint part of [#148](https://github.com/armory3d/zui/pull/148).

Add height to color wheel controls.

---

Sources/arm/Context.hx
Sources/arm/ui/UISidebar.hx

There have been some suggestions by other users that the sidebar should get a function hide it it. The current state should serve as a discussion basis whether you like that feature or not.

Hide sidebar similar to status bar

---

Sources/Main.hx
Sources/arm/App.hx
Sources/arm/ui/UINodes.hx
Sources/arm/ui/UISidebar.hx
Sources/arm/ui/UIView2D.hx

ArmorPaint part of https://github.com/armory3d/zui/pull/150

Add value slider for color picker

---

Sources/arm/ui/BoxExport.hx

Fix number of triangles in export mesh dialog

---

Assets/keymap_presets/blender.json
Assets/keymap_presets/default.json
Sources/arm/KeymapFormat.hx
Sources/arm/ui/UIMenu.hx
Sources/arm/ui/UISidebar.hx

Improved https://github.com/armory3d/armorpaint/pull/1379
- Now the shortcut is customizeable
- The shortcuts are shown in the main menu in order to make users aware of this feature

Improve menu mode shortcuts

---

Assets/locale/ja.json

If you announce the build file before updating, I can update the translation before that.

Update japanese translation file

---

armorlab/Assets/locale/tools/extract_locales.py
armorpaint/Assets/locale/tools/extract_locales.py

Fix the search path of extract_locale.py according to the folder structure change.

Fix search path in extract_locales.py

---

armorpaint/Sources/arm/ui/UIFiles.hx

Implements https://github.com/armory3d/armortools/issues/1147

Show brush icon in Browser

---

base/sources/nodes_material.ts
base/sources/parser_material.ts

Reimplementation of https://github.com/armory3d/armortools/pull/1545 for TS. The behavior is the very same.

Implement replace node
