Sources/arm/trait/ArcBallCamera.hx
I tried using this program on my tablet and noticed immediately that there was no mouse + key hotkey for zooming. I think I've made a decent work around for now with a control + middle click hotkey. You can also use control + space + right-click in order to activate the same behaviour.
=> Added Ctrl + Middle Click Zoom Shortcut

Sources/arm/ui/UIFiles.hx
There is an excess semicolon at the end of the line 203 of `UIFiles.hx` that leads to the build breaking on macOS/Darwin with:
```Shell
~/code/armorpaint/Sources/arm/ui/UIFiles.hx:207: characters 2-3 : Expected }
```
=> Removed excess semicolon.

Assets/locale/tools/extract_locales.py
The default encoding on Windows is different depending on the language, so set it to utf8.
For example, the default encoding for Japanese is cp932.
Also, since the file path has been changed, the current directory should be changed as well.
=> Fixed the encoding of the file I/O

Assets/locale/es.json, Assets/locale/ja.json, Assets/locale/zh_CN.json, Sources/arm/ui/UIToolbar.hx
Placeholders are used because the structure of sentences in English and Japanese is different.
For example, the common order in Japanese and Hangul is subject-object-verb.
=> Use placeholder in tr

Sources/arm/Translator.hx
The following code has `kha.graphics2.Graphics.fontGlyphs` as a continuous sequence will work correctly.
https://github.com/armory3d/Kromx/blob/d260a709880fc9b7e3869435e99dec7734e3d555/Sources/kha/Kravur.hx#L152-L162
Translation strings are not in the same order, so you can sort them to draw the correct characters.
=> Fixed the start position of strings in CJK languages

Libraries/syslib/Sources/arm/sys/Path.hx, Sources/arm/ui/TabFonts.hx, Sources/arm/ui/UIMenu.hx
The ttc/otf font can now be imported by https://github.com/armory3d/Kromx/pull/10 .
However, ttc font imports only font index 0.
=> Can import ttc/otf fonts

Sources/arm/Translator.hx
Change the font for CJK from `font_cjk.ttf` to [NotoSansCJK-Regular.ttc](https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJK-Regular.ttc.zip) and switch to the font of each language with the font index.
see also https://www.google.com/get/noto/help/cjk/
The font license is equal to https://github.com/armory3d/armorpaint/blob/master/Assets/licenses/license_noto.md .
You can now display different glyphs in Japanese and Chinese.
=> Switching to a language specific font in the case of CJK

Sources/arm/Translator.hx
The gumroad version does not include font_cjk.ttc, so it will not work if you switch to the cjk language.
So, switch the language if font_cjk.ttc exists.
=> Fixed a freeze when switching to cjk language in gumroad version

Sources/arm/io/ImportObj.hx
This resolves import by materials.  js.Syntax.Code behaves differently with variable scope than the deprecated function
=> declared variables outside loop

Libraries/shaderlib/Sources/arm/shader/MaterialParser.hx, Libraries/shaderlib/Sources/arm/shader/NodesMaterial.hx, Sources/arm/App.hx, Sources/arm/node/MakeMaterial.hx
Implemented the requested feature in #576. 
Resolves #576.
(Suppose to be similar to the same feature in other 3D painting apps, Hopefully right :D..)
The node is partially based on the baking mechanism of the Blur node.
Inputs are:
-  Color: the main texture to warp 
-  Strength (0.0 - 1.0): how much warp to apply
- Angle (degrees 0 - 360): the direction in which we apply the warp 
-  Mask: texture that represents the intensities of the warp for each pixel.
The effect is basically calculating the pixel with which we should replace the current pixel from the Color texture according to the other inputs.
Left side presents the effect applied to a square with a spherical grdient mask (Right side - strength == 0).
=> Warp Node feature

Sources/arm/Translator.hx
Switching to a language with a missing translation will fall back to English because the untranslated words will remain in the previous language.
An example of switching from German to Chinese
**after the fix**
**before the fix**
=> Fall back to English for untranslated words

Sources/arm/Translator.hx
Switching to CJK language changes it to font_cjk.ttc, so when you switch to non-CJK language, it changes to font.ttf
=> Changing the font when switching to a non-CJK

Sources/arm/Translator.hx
Change to font.ttf when switching from CJK to English in a pattern similar to #659
=> Changing the font when switching from CJK to English

Sources/arm/Translator.hx
Fixed the URL of the font_cjk.ttc file.
The current URL is here.
https://github.com/armory3d/armorpaint/blob/master/Assets/common/extra/font_cjk.ttc
=> Fix font_cjk.ttc url

Libraries/shaderlib/Sources/arm/shader/ShaderFunctions.hx
Regarding my prior raised issue https://github.com/armory3d/armorpaint/issues/743
This is what the brick texture looks like with this change:
It could still go a ways further to meet/match the Blender implementation (source linked in my issue above), but at least people won't feel it's completely broken.
- I took care to ensure the brick pattern remains the same as before (in dimensions and scale) so that only the colors change, for backward compatibility.
- I took care to ensure the `Fac` output did not require modification.
Hope this helps!
=> Copied noise shader logic from Blender to apply in-scope color2

Sources/arm/node/NodesBrush.hx, Sources/arm/node/brush/MathNode.hx
1. I had the problem that Absolute in brush math node did not work. So I looked into the code and saw the typo. I fixed it.
2. Modulo was called Module and did not work as well
3. I added all operations from the ordinary material math node, too (Square Root, Floor, Ceil , ...) AND arranged them in the same way to avoid confusion. 
4. I changed the behavior of Divide to match the material math node.
Finally one question not directly related to the pull request:
The convention for Atan2 is typically arctan2(y,x). The material math node calls the function with v2,v1 such that the node user has a x,y call convention for atan2. Is that intended because I would not expect that. (To be honest nobody will use the function anyway...)
=> Brush math node: fix Absolute bug and add missing operations

Sources/arm/node/NodesBrush.hx, Sources/arm/node/brush/VectorMathNode.hx
I added some missing but useful vector math operations. 
Please take at look at my reflect implementation. I'm not 100% sure whether I need the temporary variable or not. `v2.normalize()` would change v2 and 'm unsure whether this would have a global impact.
=> Add length, distance, reflect, project, divide to vector math node

Assets/export_presets/unreal.json, Sources/arm/io/ExportTexture.hx, Sources/arm/ui/BoxExport.hx
I think it is a good idea to be able to export normal maps as ordinary/OpenGl/Vulkan/Blender normal maps as well as DirectX style normal maps. As the first type is ArmorPaint's default I called the other one DirectX because it is the most prominent user of +Y normal maps and is imho the common terminology. And it is less confusing than +Y and -Y because I always mix them up. But please feel free to change the wording if you dislike it. 
I case you want to try it out:
DirectX-style bump
OpenGl-style bump
I also adapted the Unreal export preset because it uses the DirectX style normal maps. Unity uses OpenGL-style. I'm unsure about the others.
=> Add support for exporting DirectX normal maps

Sources/arm/node/NodesBrush.hx, Sources/arm/node/brush/MathNode.hx, Sources/arm/node/brush/VectorMathNode.hx
Currently the brush math and vector math nodes lack operations compared to the corresponding material nodes. This pr aligns both again such that they allow for the same operations.
Unfortunately the haxe math library does not offer hyperbolic functions. The js.math module would implement them, but I could not find any usage of javascript only modules. Therefore I implemented them by hand using the exp function.
=> Add missing operations to brush math and vector math node

Sources/arm/Layers.hx, Sources/arm/data/LayerSlot.hx, Sources/arm/ui/TabLayers.hx
This PR improves the merge down functionality for layers and fixes a few merge down related bugs.
My assumption was: Merge down must not change the visual appearance. This assumption leads to the following features that are - to my best knowledge - compatible to other common software that supports layers.
1. Now the layer system allows for merging down layers with masks to layers with masks in a correct fashion. First the masks of both layers are applied, then the results are merged.
2. Layers can be merged down on groups. In order to do that the group is merged first, then the two layers are merged.
3. Groups can be merged down on a layer.
4. Groups can be merged down on groups.
5. Now groups having only one child which has a mask are correctly merged. (Was a bug)
This fixes #1008 and …
=> Improve layer merge down

Sources/arm/data/LayerSlot.hx, Sources/arm/ui/TabLayers.hx
This pull request fixes two bugs
1. Prevent drag layer between layer and its mask fixes #1013. 
2. Fixes a bug introduced by myself. Due to the newly introduced mechanic to detect that a group is the last group on the layer stack I forgot to check whether this layer is actually a group and not an ordinary layer. Sorry for that.
=> Fix #1013 and a merge down bug

Sources/arm/data/LayerSlot.hx
This PR fixes #1003 by removing the empty group after moving the masks belonging to the laster layer in the group.
=> Move masks before removing an empty layer group

Sources/arm/App.hx
This fixes #858 by saving the window position and size before switching to fullscreen.
=> Remember window position and size on toggle fullscreen

Sources/arm/Project.hx, Sources/arm/ui/BoxExport.hx, Sources/arm/ui/BoxPreferences.hx, Sources/arm/ui/TabConsole.hx, Sources/arm/ui/TabLayers.hx, Sources/arm/ui/TabScript.hx, Sources/arm/ui/TabTextures.hx, Sources/arm/ui/UIFiles.hx, Sources/arm/ui/UIMenu.hx
Loading multiple textures, fonts, ... is somewhat painful using the open file dialog because it does not allow for selecting multiple files. This pull request changes that and allows for selecting multiple files where appropriate.
The native part is implemented in https://github.com/armory3d/armorcore/pull/29 
The key part of this PR is the extension of UIFiles.show. It adds a new paramter `openMultiple` that enables multi-selection. I'm not completely sure whether this kind of extension is the best solution. Maybe it would make sense to split open and save dialogs in separate methods.
=> Allow multiple file selection

Sources/arm/ui/UIMenu.hx
Currently ArmorPaint has issues showing the graphics cards.
The previous code assumed that there are always 30 leading bytes. This assumption is false. I checked it on different maschines. Sometimes it was less (therefore there were leading white spaces), sometimes it was more (therefore the NVID part of NVIDIA was missing in some cases).
Further more the code had problems with multiple graphics cards. Now the message should be nice and clean.
=> Improve graphics card output on windows

Sources/arm/ui/TabSwatches.hx
Color palettes are often created by starting with a base color and adding lighter and darker tones afterwards. The duplicate function for swatches makes this simpler.
Finally I have a question, too. Locally I also added an option to copy the hex color code to clipboard. To do that I exposed the `kinc_copy_to_clipboard` via a newly created function `krom_copy_to_clipboard` and used this one to achieve the desired result. Having done that I also had the idea to add a copy button to the about dialog (more precisely to the `UIBox `in case it is on linux,windows or mac and the text is copyable). The idea was to simplify reporting details (ArmorPaint version + OS/device)
Are you interested in one of these two enhancements?
=> Duplicate for swatches

Sources/arm/ui/TabConsole.hx, Sources/arm/ui/TabSwatches.hx, Sources/arm/ui/UIBox.hx
As discussed I implemented a copy feature at some useful places.
1. Swatches got an copy hex color feature to transfer hex colors to other applications/inside of ArmorPaint.
2. The console text can be copied now. This is useful copy and paste error messages without having to export them.
3. Copyable UIBoxes have a copy button now. This was mainly done for the About dialog.
Notice that the features are only available on Windows, Linux and Mac due to limitations of kinc. (I think Ctrl+C,V,X is also not available on Android and iOS, so this should be no limitation). I hope I chose the correct condition as I could not find a kha_windows | kha_linux | kha_mac condition.
=> Copy texts at various places

Sources/arm/App.hx, Sources/arm/Layers.hx, Sources/arm/ui/TabMaterials.hx
Currently creating a solid material to paint with from a swatch requires the user to create a new material, drag and drop the swatch in the node editor and rewire everything. It is way quicker to simply drag and drop a swatch in the material tab to create this material.
Similarly filling an object or parts of it with a swatch requires the user to create a material as described above and then to fill a paint layer/create a fill layer. It is way more convenient to simply drag and drop a swatch in the layers tab or the viewport.
Maybe this partly implements #1174.
=> Drag for swatch in materials and layers

Sources/arm/Project.hx, Sources/arm/io/ImportArm.hx, Sources/arm/ui/TabSwatches.hx
I improved the swatch handling in various ways
1. Fixed the bug when importing a arm file as swatch file but it actually does not contain any.
2. Added an export button based on @AlexKiryanov's idea https://github.com/armory3d/armorpaint/issues/1106#issuecomment-907467661
3. Added the option to replace or add swatches on import. Previously it was only possible to add them but not to replace them.
4. Added some tooltips to make the  swatches tab more intuitive.
=> Improve swatches

Sources/arm/ui/BoxPreferences.hx, Sources/arm/ui/TabSwatches.hx
The previews for the color wheel are very handy. This PR enhances selecting a new swatch color by enabling the preview and does the same in the theming section in the preferences dialog.
Fixes parts of https://github.com/armory3d/armorpaint/issues/1106
=> Colorwheel preview

Sources/arm/ui/TabBrowser.hx, Sources/arm/ui/TabTextures.hx
The ArmorPaint Browser is much more usable than it was some time ago. ArmorPaint also supports to open the containing folder of a texture in the OS's native file explorer. This PR adds a feature to open it in the ArmorPaint browser as well.
=> Open Texture in Browser

Sources/arm/ui/UIToolbar.hx
Fixes #1216. ArmorPaint translated the tool names twice. Once on initialization of the `toolNames` array and a second time before showing it to the user.
=> Fix double translation of tool names.

Sources/arm/ui/UINodes.hx
Currently it is possible to drag and drop a swatch to a material but the converse operation is not available. This PR adds an option to the context menu of RGB nodes to create a new swatch.
=> Add swatch context menu entry to RGB node.

Sources/arm/Context.hx, Sources/arm/Project.hx, Sources/arm/render/RenderPathPaint.hx, Sources/arm/render/Uniforms.hx, Sources/arm/ui/UIHeader.hx
This PR seperates the color picker and the swatches (`Context.swatch`). This avoids the annoying behavior of contantly destroying the swatches palette by the color picker. I also added a button to add the newly picked color as a new swatch. Maybe it would be a good idea to have a swatches icon in the future to make the button smaller.
Fixes #892
Fixes #1108
Fixes #1137
=> Improve picker

Sources/arm/ui/TabLayers.hx, Sources/arm/ui/TabMaterials.hx, Sources/arm/ui/UIHeader.hx, Sources/arm/ui/UISidebar.hx, Sources/arm/ui/UIToolbar.hx
Implements #928.
I think it helps the user a lot to hover controls and see their shortcuts and related shortcuts to more advanced functions like ruler mode or painting on a decal mask. 
You might want to change my wording a bit in case you do not like it.
=> Add shortcuts to tooltips

Sources/arm/data/LayerSlot.hx
Reordering layers is sometimes a little bit painful because it does not always work as expected. Not all valid drag and drop positions are recognized, not all recognized positions are valid and not all recognized positions do work as they should. This PR tries to end this situation entirely. I completely rewrote the code to check whether a position is valid or not and the code to rearrange the layers. I tried to get rid of all these confusing index operations that are probably the root of these issues and tried to replace it by a comprehensible and well commented system. At least I think it is very easy to understand now and is well prepared for an eventual extension to nested layer groups proposed in #1237. 
This PR fixes 
#1268
#1269
#1271
#1015
and maybe also #797 except for the fact …
=> Fix layer reordering

Sources/arm/App.hx, Sources/arm/ConfigFormat.hx, Sources/arm/ui/BoxPreferences.hx
Tried to implement #1292.
I split the camera speed in three speeds for pan, zoom and rotate as requested. I also had to adjust armorbase, see #15. There I implemented an upgrade path for older configurations, i.e. existing ArmorPaint users who rebuild their ArmorPaint after a git pull. Otherwise the users would have the problem that the camera moves weirdly because the speeds are null. The upgrade path can be removed eventually.
=> Separate camera pan, rotation and zoom speed

Sources/arm/Layers.hx, Sources/arm/ui/TabTextures.hx
Improved the textures tab
1. The "To mask" command did only work if a layer was selected and not for masks and groups. Now it is possible in all cases.
2. ArmorPaint had no obvious way of setting an envmap of an already imported texture. Thus I added a context entry to do so. I allowed it for all image formats, not just hdr. Please tell me if this option should be restricted to hdr images.
=> Improve texture tab

Sources/arm/ui/UIMenu.hx
Now it behaves like the other angle sliders. Thank you for being critical. Consistency is important,
The angles are clamped to [0,2PI] now. I.e. Both values 0 and 360 degrees are valid. Did not change it for Camera.hx but it does not matter there because it is very unlikely that the user produces exactly 2*PI by dragging the mouse and even if this case happens there is no harm if the slider shows 0 the next time the user opens the viewport menu. I tried it and the nearest I could get to 2*PI was 359.89° by mouse and this rounds to 360 so the user will not experience any difference I guess.
=> Make light angle consistent with other angles

Sources/arm/App.hx, Sources/arm/ui/TabMaterials.hx, Sources/arm/ui/TabSwatches.hx, Sources/arm/ui/UIHeader.hx, Sources/arm/ui/UINodes.hx
This PR implements two features
1. A drag and drop feature for swatches inside the Swatches Tab, i.e. swatches can be reordered now.
2. A drag and drop feature for the picker tool. The picked color can be dragged and dropped now, i.e. it is possible to drag and drop the currently picked value into the swatches tab but it is also easily create fill layers and materials from the picked value. I think this is a very cool feature and removes the need to create a swatch that can be dragged and dropped to materials or layers.
In theory we could remove the "Add swatch" button now. On the one hadn this makes the ui simpler on the other hand it is a great way to quickly add swatches and easy to understand for users. To be honest I do not really like the button that much. Maybe an icon containing a …
=> Swatch improvements

Sources/arm/io/ImportAsset.hx, Sources/arm/node/brush/BrushOutputNode.hx, Sources/arm/ui/TabTextures.hx, Sources/arm/ui/UIHeader.hx, Sources/arm/ui/UIToolbar.hx
This PR improves the color id tool a bit.
1. It fixes a unreported bug. Suppose the color id tool is selected but the user has no imported textures. If the user imports a texture the header and the viewport is not redrawn.
2. @[Wario-Ametrano](https://github.com/Wario-Ametrano) proposed the idea to show the currently picked color in the toolbar in https://github.com/armory3d/armorpaint/issues/1069 . I really like this ideas as it makes the color id tool much easier to use and gives a visual hint that a color id is active. I did not implement his idea to have a context menu for the color id tool to clear the picked color. Imho this would be not only be inconsistent but also a very unusual option to have. While some applications have context menus for their toolbar icon these menus are …
=> Improve color id tool

Sources/arm/ui/TabBrushes.hx, Sources/arm/ui/TabFonts.hx, Sources/arm/ui/TabLayers.hx, Sources/arm/ui/TabMaterials.hx, Sources/arm/ui/TabSwatches.hx, Sources/arm/ui/TabTextures.hx, Sources/arm/ui/UIMenu.hx
Remade the pull request #1313 because there were already more merge commits than actual commits.
1. Added the delete shortcuts to the context menus. They were missing and I think it is better to be explicit about features.
2. Added the shortcuts for light angle and env angle as tooltip.
3. Added an explanation for using the different camera modes. The tooltip is a bit long, that's why I split the string into two. It should also simplify translation. Nonetheless the tooltip is great imho as it explains the usage in a compact and comprehensible way. If someone does not know the shortcuts or wants to look them up it's very easy to do now. Also the fly mode is only explained in code but nowhere in ui. That should not happen.
=> Tooltip improvements

Sources/arm/App.hx, Sources/arm/Layers.hx, Sources/arm/Project.hx, Sources/arm/data/LayerSlot.hx, Sources/arm/ui/TabMaterials.hx, Sources/arm/ui/TabSwatches.hx, Sources/arm/ui/UIHeader.hx
I started implementing pbr swatches. 
This PR includes the following features
1. The color picker produces pbr swatches now.
2. The materials tab and the layers tab accept pbr swatches now.
3. The swatches tab has a ui for dealing with pbr swatches now. All commands are pbr swatch ready, too.
4. I added two commands to the context menu: One to create a new material from swatch, one to create a new layer from swatch. These two are not only pretty handy but probably a nice way to show the user what to do with swatches. Suppose the user does not understand the drag and drop feature the swatches become useless. It's also good for the touch versions of ArmorPaint.
5. Consistency with the old non-pbr swatch implementation: Because the other channels get default values there is no change in …
=> Pbr swatches

Sources/arm/App.hx, Sources/arm/Context.hx, Sources/arm/ui/TabSwatches.hx, Sources/arm/ui/UINodes.hx, Sources/arm/ui/UISidebar.hx
Improved the swatches and the picker a bit
- Now the picker for swatches supports pbr swatches
- For some reason I do not understand why I didn't see it my pbr swatch ui did not work
- Made the picker more intuitive: now there is a picker icon next to the mouse, picking can be cancelled by right click and the tool is switched back to the previous one. 
I think it is way more intuitive now
QUESTION: Tried Alpha instead of opacity
Idea is good imho but inconsistent. Either one would change opacity to alpha in all color related situations or we keep it like it is now. My proposal: keep it the way it is because opacity does also influence other channels and not only RGB.
=> Improve swatches and picker

Sources/arm/Project.hx, Sources/arm/io/ExportGpl.hx
Implemented a gimp color palette exporter (gpl files). I think it is useful to be able to share the palette with other programs. Wrote the exporter first in order to get used to the (honestly simple) format. There are two types of gpl file, older ones and newer ones. This exporter uses the newer one. Will implement the importer the next days.
=> Add gimp color palette exporter

Sources/arm/ui/UINodes.hx
Currently ArmorPaint always connects to the first socket if the user drags an edge, releases the mouse and creates a new node. Imho ArmorPaint could be a bit smarter and connect to the first matching socket if possible.
Example:
The correct socket is chosen now (at least for the typical situations)
=> Connect to best matching socket on link drag

Sources/arm/History.hx, Sources/arm/Layers.hx, Sources/arm/data/LayerSlot.hx, Sources/arm/ui/TabLayers.hx
This PR tries to fix several issues related to layers and improves a few things.
1. New groups are not always available. Therefore it is better to grey out if not available.
2. Layer delete has several issues. It does not work well with group masks, the undo and redo system is broken and it was not possible to delete in all valid cases resp. there have been cases where deleting shouldn't have been available. This PR sorts them out and fixes  #989. Maybe my undo-redo approach is not the most efficient way but it works reliably as far as I can see.
3. Duplicate layers did not work well with group masks. Fixed these issues and refactored a bit.
4. canMergeDown could use a little bit of love to become more readable. Also it did not cover all cases I think.
5. Merging groups and merge down did …
=> Improve layers

Sources/arm/Context.hx, Sources/arm/ui/UIMenu.hx, Sources/arm/ui/UISidebar.hx
Implemented https://github.com/armory3d/armorpaint/issues/1347
By pressing "ctrl+m" a mode selector is shown. Really love this concept and maybe it is useful elsewhere, too.
We might want to tweak the shortcuts. Currently ctrl+m is not customizeable yet and unsure whether my shortcut choice is perfect yet, too.
=> Shortcut for viewport mode

Sources/arm/History.hx, Sources/arm/Project.hx, Sources/arm/ui/UINodes.hx
Currently material groups have the property to get auto deleted once they are not used anymore.
This leads to unwanted behavior:
- Build a meaningful group.
- Remove the material the group is used in.
- Try to reuse it in a newly created material. -> the group is gone and there is no way to restore it.
Other scenarios where this happens are https://github.com/armory3d/armorpaint/issues/1209 and https://github.com/armory3d/armorpaint/issues/1214. Basically they cut the last appearance of a group, it gets deleted and once the user wants to paste it, there is a problem. Both get fixed by this PR.
What did I change?
1. Removed the auto remove feature.
2. Added an option to remove unused groups. 
3. Added undo-redo for the operation. This prevents two problems: 
3.1 If a group node is deleted, …
=> Delete material groups

Sources/arm/ui/TabLayers.hx, Sources/arm/ui/TabMaterials.hx, Sources/arm/ui/UISidebar.hx
It is always painful to select materials and layers via shortcut because the user has to count.
Let's change this and make it intuitive. Hold shift (or a custom shortcut) to preview material numbers. Hold alt (or custom shortcut) to preview layer numbers.
=> Select shortcuts

Sources/arm/ui/TabBrowser.hx, Sources/arm/ui/UINodes.hx
This PR implements live search for the browser proposed by @sanya-2005 in #1222
In addition I added `ctrl+f` as a non customizable shortcut to start searching and `esc` to stop it again.
Aditionally I changed the node search to use the new live text input feature. It makes the code shorter and more readable imho. From an ArmorPaint perspective you could make `textSelected` a private attribute of zui.
=> Live search for browser

Sources/arm/ui/UIFiles.hx
The browser has no visual feedback for selected materials in contast to other items. https://github.com/armory3d/armorpaint/issues/814 proposes this feature.
=> Add border to selected materials in browser

Sources/arm/ui/TabLayers.hx
Is there any issue if we increase the active area to drag and drop a layer slot? Also the context menu can be triggered in a bigger rectangle now.
Fixes https://github.com/armory3d/armorpaint/issues/1165
=> Increase active layer slot area

Sources/arm/ui/UIHeader.hx
Tried to improve the text tool and to (practically) fix https://github.com/armory3d/armorpaint/issues/1154
1. Now live update is used to update the text decal while typing
2. The textInput's width is increased if it is active. Imho the current width is too small. The factor 3 was determined by comparing the overall width of all tool's headers. Currently the picker tool is is the tool with the highest width.
=> Improve text tool

Sources/arm/History.hx
Fixes #1089 and partially #1382. More specifically, this PR fixes an UI freeze when undoing "Merge Down" command when merging down a layer with one or more masks.
The cause of the freeze was the asymmetry between Layers.mergeDown and History.mergeLayers. Layers.mergeDown applies all of the masks both of layers have, and History.mergeLayers didn't take that into account. Because of that, the layer that was saved into the undo step was off by the number of the masks applied, which resulted in an exception being thrown when History.undo tried to delete a non-existent layer.
This PR does not fix restoring the mask layers themselves, though (#1001).
=> Fix a freeze when undoing Merge Down if top layer has a mask

armorpaint/Sources/arm/ui/TabBrowser.hx, armorpaint/Sources/arm/ui/UIFiles.hx
I added a context menu as suggested in https://github.com/armory3d/armortools/issues/814
The context menu differs by file type. Currently the only cases are texture or non-texture. 
- In the texture case some convenience functions are added to the context menu similar to the textures tab.
- The context menu is particularly useful for folders. Right click + import on a folder to import the content of a folder as new material (just as it is the case for drag and drop with folders)
=> Add context menu to browser

armorpaint/Sources/arm/ui/UIFiles.hx
Currently ArmorPaint's browser has no thumbnails for textures (see https://github.com/armory3d/armortools/issues/814). This PR implements a starter for this feature.
Limitations:
1. The `iconMap` is not "garbage collected". But the very same holds for the cloud, too.
2. The numbnails have a fixed resolution independent of the ui scale. Implementing this feature would require to regenerate/delete the thumbails if the ui scale is changed.
=> Texture preview for browser

armorpaint/Sources/arm/ui/UINodes.hx
I made the node search case insensitive. Now this works:
Previously nothing was found.
=> Make node search case insensitive

armorpaint/Sources/arm/App.hx, armorpaint/Sources/arm/ui/TabLayers.hx
This PR implements a drag and drop system for materials and swatches in the layer stack similar to reordering layers via drag and drop. 
I think that's cool 😎 and more intuitive than the previous system.
Drop in viewport is not changed.
Resolves https://github.com/armory3d/armortools/issues/1014
=> Drop material and swatches at position in layers

base/Sources/Main.hx
Fixes compile error for Metal by enabling function definitions for `kha_metal` flag
Error was:
```
base/Sources/Main.hx:35: characters 3-16 : Unknown identifier : embedRaytrace
base/Sources/Main.hx:37: characters 3-20 : Unknown identifier : embedRaytraceBake
```
=> Fixes compile error for Metal

.github/workflows/android_opengl.yml, .github/workflows/ios_metal.yml, .github/workflows/linux_vulkan.yml, .github/workflows/macos_metal.yml, .github/workflows/windows_direct3d12.yml
Fix warning in with current action:
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
=> Update actions/checkout to v3

armorlab/README.md
Fixed typo in ArmorLab compile instructions for MacOS where it says "ArmorPaint" instead of "ArmorLab" in a path name.
=> Update README.md for ArmorLab

base/sources/backends/direct3d12_gpu.c
When trying to build the project on Windows there's a few errors related to the use of renderTarget and render_target, a typo where -> became -. and a semicolon was forgotten in one of the lines
=> Fix direct3d12_gpu.c

armorpaint/assets/plugins/import_gltf_glb.js, armorpaint/plugins/io_gltf/cgltf.c, armorpaint/plugins/plugins.c
This PR adds a _path_ argument to `io_gltf_parse` to ensure *.gltf files with additional, external *.bin files are loaded, which was required for my pipeline. I also encountered some meshes with null primitives, so the code has been modified to instead search for the first initialised primitive in the mesh and load that. The vertex count is now also explicitly set based on the positions buffer.
I understand there may be some interactions that I didn't forsee with other platforms and the like (such as using different forms of IO where `cgltf` may not be able to search the filesystem for binary files), let me know and I am willing to fix these up as necessary.
=> Allow importing *.gltf files with additional binary data
